Node/src/main/java/de/iai/ilcd/model/security/User.java
package de.iai.ilcd.model.security;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.HashMap; 
import java.util.Date;
import java.util.List;
import java.util.Map;

import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.CollectionTable;
import javax.persistence.Column;
import javax.persistence.ElementCollection;
import javax.persistence.Embedded;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.MapKeyColumn;
import javax.persistence.PostLoad;
import javax.persistence.PostUpdate;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.apache.commons.lang.ObjectUtils;

import de.iai.ilcd.util.SodaUtil;

/**
 * 
 * @author clemens.duepmeier
 */
@Entity
@Table( name = "user" )
public class User implements ISecurityEntity, Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue( strategy = GenerationType.IDENTITY )
	private Long id;

	@Column( unique = true )
	private String userName;

	@Column( name = "PASSWORD_HASH" )
	private String passwordHash;

	@Column( name = "PASSWORD_HASH_SALT" )
	private String passwordHashSalt;

	private String firstName;

	private String lastName;

	private String title;

	@Enumerated( EnumType.STRING )
	private Gender gender = null;

	private String institution;
	
	private String phone;
	
	private String email;

	private String registrationKey;

	private String dsPurpose;

	private String jobPosition;
	
	@Column( unique = true)
	private String apiKey;
	
	@Column( name = "apikeyexpiry")
	private Date apiKeyExpiry;
	
	@Column( name = "apikeyallowed")
	private Boolean apiKeyAllowed = true;

	@Transient
	private Boolean licenseConditions = false;

	@Column( name = "acceptedAddTerms")
	private Boolean acceptedAdditionalTerms = false;

	@Embedded
	private Address address = new Address();

	@ManyToMany( mappedBy = "users", fetch = FetchType.EAGER, cascade = { CascadeType.PERSIST, CascadeType.MERGE, CascadeType.REFRESH, CascadeType.DETACH } )
	// Does not contain CascadeType.REMOVE
	private List<UserGroup> groups = new ArrayList<UserGroup>();

	@Basic
	@Column( name = "super_admin_permission" )
	private boolean superAdminPermission;

	/**
	 * The organization of the user
	 */
	@ManyToOne( optional = true )
	@JoinColumn( name = "organization", nullable = true )
	private Organization organization;
	
	@Basic
	@Column( name = "privacy_policy_accepted" )
	private Boolean privacyPolicyAccepted;
	
	@Basic
	@Column( name = "password_expired")
	private Boolean passwordExpired;
	

	@ElementCollection( targetClass = String.class )
	@CollectionTable( name = "user_sector", joinColumns = @JoinColumn( name = "User_ID" ))
	private List<String> sector = new ArrayList<String>();
	
	@ElementCollection
	@CollectionTable( name = "user_acceptedaddterms", joinColumns = @JoinColumn( name = "User_ID" ))
	@MapKeyColumn(name="additionalterm")
	@Column(name="accepted")
	private Map<String, Boolean> acceptedAdditionalTermsMap = new HashMap<String, Boolean>();

	@Basic
	@Column( name = "sector_other" )
	private String sectorOther;

	@Column( name = "resetkey" )
	private String resetKey;
	
	@Column( name = "resettimestamp" )
	private Date resetTimestamp;
	
	
	@Override
	public Long getId() {
		return this.id;
	}

	public void setId( Long id ) {
		this.id = id;
	}

	public Address getAddress() {
		return this.address;
	}

	public void setAddress( Address address ) {
		this.address = address;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail( String email ) {
		this.email = email;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName( String firstName ) {
		this.firstName = firstName;
	}
	
	public String getInstitution() {
		return institution;
	}
	
	public void setInstitution(String institution) {
		this.institution = institution;
	}
	
	public String getPhone() {
		return phone;
	}
	
	public void setPhone(String phone) {
		this.phone = phone;
	}

	public Gender getGender() {
		return this.gender;
	}

	public void setGender( Gender gender ) {
		this.gender = gender;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName( String lastName ) {
		this.lastName = lastName;
	}

	public String getPasswordHash() {
		return this.passwordHash;
	}

	public void setPasswordHash( String passwordHash ) {
		this.passwordHash = passwordHash;
	}

	public String getPasswordHashSalt() {
		return this.passwordHashSalt;
	}

	public void setPasswordHashSalt( String passwordHashSalt ) {
		this.passwordHashSalt = passwordHashSalt;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle( String title ) {
		this.title = title;
	}

	public String getUserName() {
		return this.userName;
	}
	
	public String getResetKey() {
		return resetKey;
	}
	
	public void setResetKey(String resetKey) {
		this.resetKey = resetKey;
	}
	
	public Date getResetTimestamp() {
		return resetTimestamp;
	}
	
	public void setResetTimestamp(Date resetTimestamp) {
		this.resetTimestamp = resetTimestamp;
	}


	/**
	 * {@inheritDoc}
	 */
	@Override
	public String getDisplayName() {
		return this.userName;
	}

	public void setUserName( String userName ) {
		this.userName = userName;
	}

	public String getRegistrationKey() {
		return this.registrationKey;
	}

	public void setRegistrationKey( String registrationKey ) {
		this.registrationKey = registrationKey;
	}

	public boolean isActivated() {
		return registrationKey == null;
	}

	public List<UserGroup> getGroups() {
		return this.groups;
	}

	protected void setGroups( List<UserGroup> groups ) {
		this.groups = groups;
	}

	public String getDsPurpose() {
		return this.dsPurpose;
	}

	public void setDsPurpose(String dspurpose) {
		this.dsPurpose = dspurpose;
	}

	public String getJobPosition() {
		return this.jobPosition;
	}

	public void setJobPosition( String jobPosition ) {
		this.jobPosition = jobPosition;
	}

	public Boolean getAcceptedAdditionalTerms() {
		return acceptedAdditionalTerms;
	}

	public void setAcceptedAdditionalTerms(Boolean acceptedAdditionalTerms) {
		this.acceptedAdditionalTerms = acceptedAdditionalTerms;
	}
	
	public void setAcceptedAdditionalTermsMap(Map<String, Boolean> acceptedAdditionalTermsMap) {
		this.acceptedAdditionalTermsMap= acceptedAdditionalTermsMap;
	}
	
	public Map<String, Boolean> getAcceptedAdditionalTermsMap() {
		return this.acceptedAdditionalTermsMap;
	}

	
	public String getApiKey() {
		return apiKey;
	}
	
	public void setApiKey(String apiKey) {
		this.apiKey = apiKey;
	} 
	
	public Date getApiKeyExpiry() {
		return apiKeyExpiry;
	}
	
	public String getApiKeyExpiryString() {
		if (apiKeyExpiry != null) {
			return apiKeyExpiry.toString();
		}
		return "---";
	}
	
	public void setApiKeyExpiry(Date apiKeyExpiry) {
		this.apiKeyExpiry = apiKeyExpiry;
	}
	
	public Boolean isApiKeyAllowed() {
			return apiKeyAllowed;

	}

	public void setApiKeyAllowed(boolean apiKeyAllowed) {
		this.apiKeyAllowed = apiKeyAllowed;
	}
	
	/**
	 * 
	 * @param group
	 */
	public void addToGroup( UserGroup group ) {
		if ( !this.groups.contains( group ) ) {
			this.groups.add( group );
			group.addUser( this );
		}
	}

	public void removeFromGroup( UserGroup group ) {
		if ( this.groups.contains( group ) ) {
			this.groups.remove( group );
		}
	}

	public void removeFromAllGroups() {
		List<UserGroup> allGroups = new ArrayList<UserGroup>();
		allGroups.addAll( this.groups );
		for ( UserGroup group : allGroups ) {
			group.removeUser( this ); // this removes the group also locally
		}
	}

	/**
	 * Get the organization of this user
	 * 
	 * @return organization of this user
	 */
	public Organization getOrganization() {
		return this.organization;
	}

	/**
	 * Set the organization of this user
	 * 
	 * @param organization
	 *            organization of this user to set
	 */
	public void setOrganization( Organization organization ) {
		if ( ObjectUtils.equals( this.organization, organization ) ) {
			return;
		}
		Organization oldOrg = this.organization;
		this.organization = organization;

		if ( oldOrg != null ) {
			oldOrg.removeUser( this );
		}

		if ( this.organization != null ) {
			this.organization.addUser( this );
		}
	}
	
	public boolean isPrivacyPolicyAccepted() {
		return this.privacyPolicyAccepted != null ? this.privacyPolicyAccepted : false;
	}
	
	public void setPrivacyPolicyAccepted(boolean privacyPolicyAccepted) {
		this.privacyPolicyAccepted = privacyPolicyAccepted;
	}
	
	public Boolean isPasswordExpired() {
		return passwordExpired;
	}

	public void setPasswordExpired(Boolean passwordExpired) {
		this.passwordExpired = passwordExpired;
	}

	public Boolean getLicenseConditions() {
		return licenseConditions;
	}

	public void setLicenseConditions(Boolean licenseConditions) {
		this.licenseConditions = licenseConditions;
	}
	
	public List<String> getSector() {
		return sector;
	}

	public void setSector(List<String> sector) {
		this.sector = new ArrayList<String>(sector);
	}
	
	public String getSectorAsString() {
		StringBuffer buf = new StringBuffer();
		for (String s : this.sector) {
			if (buf.length() != 0) {
				buf.append(";");
			}
			buf.append(s);
		}
		return buf.toString();
	}

	public String getSectorOther() {
		return sectorOther;
	}

	public void setSectorOther(String sectorOther) {
		this.sectorOther = sectorOther;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
		result = prime * result + ((this.userName == null) ? 0 : this.userName.hashCode());
		return result;
	}

	@Override

Node/src/main/java/de/iai/ilcd/webgui/controller/admin/CustomReportsBean.java
package de.iai.ilcd.webgui.controller.admin;

import java.io.IOException;
import java.util.List;

import javax.faces.bean.ApplicationScoped;
import javax.faces.bean.ManagedBean;
import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;

import org.joda.time.DateTime;
import org.joda.time.format.DateTimeFormat;
import org.joda.time.format.DateTimeFormatter;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.web.context.WebApplicationContext;
import org.springframework.web.jsf.FacesContextUtils;

import de.iai.ilcd.model.common.ReportConfig;
import de.iai.ilcd.service.CustomReportService;

/**
 * The managed bean for retrieving customized reports.
 * 
 * @author sarai
 *
 */
@ManagedBean(name = "customReportsBean")
@ApplicationScoped
public class CustomReportsBean {

	private Logger log = LoggerFactory.getLogger(this.getClass());
	
	private CustomReportService customReportService;

	public CustomReportsBean() {
		WebApplicationContext ctx = FacesContextUtils.getWebApplicationContext(FacesContext.getCurrentInstance());
		this.customReportService = ctx.getBean(CustomReportService.class);
	}

	public List<ReportConfig> getReportConfigs() {
		return customReportService.getReportConfigs();
	}

	/**
	 * Checks whether custom reports are enabled.
	 * 
	 * @return true if at least one custom report is set.
	 */
	public boolean isCustomReportsEnabled() {
		return (customReportService.getReportConfigs() != null)
				&& !customReportService.getReportConfigs().isEmpty();
	}

	/**
	 * Executes an SQL query for a report and write result directly to the response
	 * 
	 * @param request
	 *            The request to execute
	 * @param fileName
	 *            he desired file name of csv result
	 * 
	 */
	public void executeSQL(final ReportConfig report) {
		try {			
			String fileName = new String(report.getFileName()).replace(" ", "_");
			if (report.isTimeStampSuffix()) {
				DateTimeFormatter dtf = DateTimeFormat.forPattern("yyyy-MM-dd_HH-mm");
				fileName +=  "_" + dtf.print(new DateTime());
			}
			fileName += ".csv";
			if (log.isDebugEnabled())
				log.debug("filename is " + fileName);

			FacesContext facesContext = FacesContext.getCurrentInstance();
			ExternalContext externalContext = facesContext.getExternalContext();
			externalContext.setResponseContentType("text/csv");
			externalContext.setResponseHeader("Content-Disposition", "attachment; filename=\"" + fileName + "\"");

			customReportService.executeSQLQuery(report, externalContext.getResponseOutputStream());
			
			facesContext.responseComplete();
		} catch (IOException e) {
			log.error("Error writing response", e);
			if (log.isDebugEnabled()) 
				e.printStackTrace();
		}
	}
	
	public CustomReportService getReportService() {
		return this.customReportService;
	}

}

Node/src/main/webapp/admin/addressInfoPanel.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
  xmlns:h="http://java.sun.com/jsf/html"
  xmlns:p="http://primefaces.org/ui"
  xmlns:f="http://java.sun.com/jsf/core"
  xmlns:ui="http://java.sun.com/jsf/facelets">
<!-- 
ui:params:
	- countries: country list
	- chosenCountry: chosen country
	- address: address instance
 -->
<ui:param name="backingBean" value="#{contactListHandler}" />
    <p:panel header="#{i18n['admin.user.addrInfo']}">
        <h:panelGrid columns="2">
            <p:outputLabel value="#{i18n['admin.user.country']}:" for="country" />
            <!-- Fix with 150px due to problems with tabs: (usage with orgEntry)
                 dynamic=true for tabs ==> null value set for selectOneMenu
                 dynamic=false ==> selectOneMenu styling bug, set manually -->
            <p:selectOneMenu style="width:150px" id="country" value="#{chosenCountry}" converter="geoAreaConverter">
                <f:selectItem itemLabel="#{i18n['common.select.hint']}" itemValue="0" />
                <f:selectItems value="#{countries}" var="country" itemLabel="#{country.name}" itemValue="#{country}" />
            </p:selectOneMenu>
        </h:panelGrid>
        <h:panelGrid columns="4">
            <p:outputLabel value="#{i18n['admin.user.zipCode']}:" for="zipCode" />
            <p:inputText id="zipCode" value="#{address.zipCode}" maxlength="50" size="10" />
            <p:outputLabel value="#{i18n['admin.user.city']}:" for="city" />
            <p:inputText id="city" value="#{address.city}" maxlength="50" size="30" />
        </h:panelGrid>
        <h:panelGrid>
            <p:outputLabel value="#{i18n['admin.user.streetAddr']}:" for="streetAddr" />
            <p:inputTextarea id="streetAddr" value="#{address.streetAddress}" cols="72" rows="10" />
        </h:panelGrid>
    </p:panel>
</ui:composition>

Node/src/main/webapp/admin/sodaMenuBarOrg.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:soda="http://java.sun.com/jsf/composite/sodacomp"
	xmlns:ui="http://java.sun.com/jsf/facelets">

	<soda:menuBar
		action_saveEntry="#{orgHandler.saveEntry}"
		action_saveCloseEntry="#{orgHandler.saveCloseEntry}"
		action_saveNewEntry="#{orgHandler.saveNewEntry}"
		btnLabel_manageList="#{i18n['admin.org.manageList']}"
		btnOutcome_manageList="#{url.org.manageList}"
		spacerHeight_afterToolbar="#{spacerHeight_afterToolbar}"
		spacerHeight_beforeToolbar="#{spacerHeight_beforeToolbar}"
		update="@(#messages), @(#orgTabs)" />

</ui:composition>

Node/src/main/webapp/admin/userEntry.xhtml
<?xml version='1.0' encoding='UTF-8' ?>

<!-- 
ui:params:
	- nameEditable: name field editable?
	- pwShown: show password field
	- showOrganisation: show organisation
	- handler: handler to use (must have getUser method)
	- requireSector: whether to require entry for sector
 -->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:pe="http://primefaces.org/ui/extensions"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:shiro="http://shiro.apache.org/tags">
    <ui:composition>
        <p:panel header="#{i18n['admin.user.loginInfo']}">
            <h:panelGrid columns="4">
                <p:outputLabel value="#{i18n['common.user.loginName']}:" for="nameOut" rendered="#{not nameEditable}" />
                <p:outputLabel id="nameOut" value="#{handler.user.userName}" rendered="#{not nameEditable}" style="padding-left:0.5em;" />
                
                <p:outputLabel value="#{i18n['common.user.loginName']}:" for="nameIn" rendered="#{nameEditable}" />
                <p:inputText id="nameIn" value="#{handler.user.userName}" required="true" requiredMessage="#{i18n['admin.user.requiredMsg.loginName']}" maxlength="40" size="20" rendered="#{nameEditable}" />
                
                <p:outputLabel value="#{i18n['common.email']}:" for="email" />
                <p:inputText id="email" value="#{handler.user.email}" required="true" requiredMessage="#{i18n['admin.user.requiredMsg.email']}" validatorMessage="#{i18n['admin.user.validatorMsg.email']}" maxlength="80" size="40">
                    <f:validateRegex pattern="[\w\.-]*[a-zA-Z0-9_]@[\w\.-]*[a-zA-Z0-9]\.[a-zA-Z][a-zA-Z\.]*[a-zA-Z]" />
                </p:inputText>
                
                <p:outputLabel rendered="#{pwShown}" value="#{i18n['common.user.passw']}:" for="passw" />
                <p:password rendered="#{pwShown}" id="passw" value="#{handler.plainPassword}" required="#{handler.createView}" requiredMessage="#{i18n['admin.user.requiredMsg.passw']}" feedback="false" minLength="" maxlength="20" size="20" >
                	<f:validator validatorId="de.iai.ilcd.webgui.validators.PasswordRequirementsValidator" />
                </p:password>
                
                <p:outputLabel rendered="#{pwShown}" value="#{i18n['admin.user.repeatPassw']}:" for="repeatPassw" />
                <p:password rendered="#{pwShown}" id="repeatPassw" value="#{handler.verifyPassword}" feedback="false" minLength="" maxlength="20" size="20" /> 
            </h:panelGrid>
            <p:outputLabel style="font-size: smaller;" value="#{i18n['admin.user.passwInfo']}." rendered="#{pwShown}" />
        </p:panel>

        <p:panel header="#{i18n['admin.user.personalInfo']}">
            <h:panelGrid columns="6">
                    <p:outputLabel value="#{i18n['admin.title']}:" for="title" />
                    <p:inputText id="title" value="#{handler.user.title}" maxlength="40" size="5" />
                    
                    <p:outputLabel value="#{i18n['admin.user.firstName']}:" for="firstName" />
                    <p:inputText id="firstName" value="#{handler.user.firstName}" required="#{conf.requireNameForRegistration}" requiredMessage="#{i18n['admin.user.requiredMsg.firstName']}" maxlength="40" size="15" />
                    
                    <p:outputLabel value="#{i18n['admin.user.lastName']}:" for="lastName" />
                    <p:inputText id="lastName" value="#{handler.user.lastName}" required="#{conf.requireNameForRegistration}" requiredMessage="#{i18n['admin.user.requiredMsg.lastName']}" maxlength="40" size="20" />
            </h:panelGrid>
            <h:panelGrid columns="2">
                <p:outputLabel value="#{i18n['admin.user.gender']}:" for="gender" style="margin-right:1em;" />
                <p:selectOneRadio id="gender" value="#{handler.user.gender}" styleClass="radioLabelPadding">
                    <f:selectItem itemLabel="#{i18n['admin.user.gender.female']}" itemValue="f" />
                    <f:selectItem itemLabel="#{i18n['admin.user.gender.male']}" itemValue="m" />
                    <f:selectItem itemLabel="#{i18n['admin.user.gender.other']}" itemValue="o" />
                </p:selectOneRadio>
          	        
          	    <p:outputLabel value="#{i18n['common.user.jobposition']}:" for="jobposition" />
                <p:inputText id="jobposition"
                	    value="#{handler.user.jobPosition}"
                              required="false"
                              requiredMessage="#{i18n['common.user.requiredMsg.jobposition']}"
                              maxlength="80"
                              size="40" />          
            </h:panelGrid>
            <h:panelGrid columns="2"> 
                              
               	<p:outputLabel value="#{i18n['admin.user.institution']}:" for="institution" />
                <p:inputText id="institution" value="#{handler.user.institution}" maxlength="100" size="75"/>
            </h:panelGrid>
             
            <h:panelGrid columns="2">            
            	<p:outputLabel value="#{i18n['admin.user.phone']}:" for="phone" />
                <p:inputText id="phone" onkeypress="if(event.which &lt; 48 || event.which &gt; 57) return false;" value="#{handler.user.phone}" maxlength="20" size="20" />	                
            </h:panelGrid>
        </p:panel>
        <p:panel header="#{i18n['common.user.comments']}">
	        <h:panelGrid>
                <p:outputLabel value="#{i18n['common.user.dspurpose']}:" for="dspurpose" />
                <p:inputTextarea id="dspurpose"
                                 value="#{handler.user.dsPurpose}"
                                 cols="72"
                                 rows="10" maxlength="255" />
            </h:panelGrid>
        </p:panel>
        <p:panel header="#{i18n['admin.user.accessRight']}" rendered="#{user.hasSuperAdminPermission()}">
        	
        <p:panelGrid columns="1" styleClass="ui-noborder">
	        <p:selectBooleanCheckbox value="#{handler.entry.superAdminPermission}" itemLabel="#{i18n['admin.user.accessRight.superadmin']}" disabled="#{handler.entry.id == Constants.ADMIN_ID}"/>
	        
	       	<p:spacer height="10"/>
	        	
	        <p:selectBooleanCheckbox value="#{edit ? handler.apiKeyAllowed: false}" itemLabel="#{i18n['admin.user.apikey.allowed']}" disabled="#{not edit}">
	        <p:ajax update="apiKey"/>
	        </p:selectBooleanCheckbox>
        	
        </p:panelGrid>
        	
        <h:panelGroup id="apiKey">
        <p:panel rendered="#{edit ? handler.apiKeyAllowed: false}">
	        <h:panelGrid columns="2"  rendered="#{handler.apiKeyAllowed}">
	        	<h:outputText value="#{i18n['admin.user.apikey.token']}:"/>
	        	<p:inputTextarea id="tokenOutput" value="#{handler.token}" readonly="true" cols="72"/>
	        </h:panelGrid>	
	        	
        		<pe:clipboard id="clipCopy" trigger="btnCopy" action="copy" target="tokenOutput">  
		           <p:ajax event="success" listener="#{userHandler.successListener}" />  
		           <p:ajax event="error" listener="#{userHandler.errorListener}" />  
        		</pe:clipboard>  
        		<div class="buttonRight">
        			<p:commandButton value="#{i18n['admin.user.apikey.generate']}" action="#{handler.generateApiKey}" ajax="false" />
	        		<p:commandButton id="btnCopy" value="Copy" icon="fa fa-copy" />  
	        	</div>
	        	<h:outputText value="#{i18n['admin.user.apikey.expiry']}:"/>
	        	<h:outputText value="#{handler.entry.apiKeyExpiryString}" />	
	        </p:panel>
        </h:panelGroup>
        
        </p:panel>
		Basic Application Setup
        <p:panel header="#{i18n['admin.org.info']}" rendered="#{showOrganisation}">
            <ui:fragment rendered="#{empty userHandler.allOrganizations}">
                <h:panelGrid columns="2">
                    <p:outputLabel for="org" value="#{i18n['admin.org']}:" />
                    <p:outputLabel id="org" value="#{handler.user.organization.name}" />
                </h:panelGrid>
            </ui:fragment>
            <ui:fragment rendered="#{not empty userHandler.allOrganizations}">
                <h:panelGrid columns="2">
                    <p:outputLabel for="orgSelect" value="#{i18n['admin.org']}:" />
                    <p:selectOneMenu id="orgSelect" value="#{handler.user.organization}" converter="orgConverter">
                        <f:selectItem itemLabel="#{i18n['common.select.hint']}" noSelectionValue="true" />
                        <f:selectItems value="#{userHandler.allOrganizations}" var="o" itemLabel="#{o.name}" itemValue="#{o}" />
                        <p:ajax event="change" process="@this" update="orgChangeHint" />
                    </p:selectOneMenu>
                </h:panelGrid>
                <p:outputLabel id="orgChangeHint" value="#{i18n['admin.user.hint.orgChange']}" styleClass="#{userHandler.organizationChangeRequiresGroupRemovals?'':'ui-helper-hidden'}" />
            </ui:fragment>
        </p:panel>
        
        <ui:fragment rendered="#{conf.sectors}">
	        <p:panel id="sector" header="#{i18n['public.user.registration.sector']}">
	            <h:panelGrid columns="1">
		            <p:outputLabel for="sectorSelect" value="#{i18n['public.user.registration.sector.info']}" />
		            <p:selectManyMenu id="sectorSelect" value="#{handler.user.sector}" required="#{requireSector}" requiredMessage="#{i18n['public.user.registration.sector.required']}" style="width: 400px">
		                <f:selectItem itemLabel="#{i18n['common.select.hint']}" noSelectionValue="true" />
		                <f:selectItems value="#{userHandler.allSectors}" var="o" itemLabel="#{o}" itemValue="#{o}" />
		            </p:selectManyMenu>
		
		            <div style="margin-top: 1em">
		                <p:outputLabel for="sectorOther" value="#{i18n['public.user.registration.sector.other']}:"/>
		                <div>
		                    <p:inputText id="sectorOther" value="#{handler.user.sectorOther}" maxlength="100" style="width: 400px" />
		                </div>
		            </div>
		        </h:panelGrid>
	        </p:panel>
		</ui:fragment>     
		   
		<ui:include src="addressInfoPanel.xhtml">
			<ui:param name="countries" value="#{handler.countries}" />
			<ui:param name="chosenCountry" value="#{handler.chosenCountry}" />
			<ui:param name="address" value="#{handler.user.address}" />
		</ui:include>
    </ui:composition>
</html>