Node/src/main/java/de/iai/ilcd/model/adapter/dataset/AbstractDatasetAdapter.java
package de.iai.ilcd.model.adapter.dataset;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import de.fzk.iai.ilcd.service.client.impl.vo.dataset.DataSetVO;
import de.fzk.iai.ilcd.service.model.IDataSetListVO;
import de.fzk.iai.ilcd.service.model.IDataSetVO;
import de.iai.ilcd.model.adapter.ClassificationAdapter;
import de.iai.ilcd.model.adapter.LStringAdapter;

public abstract class AbstractDatasetAdapter<T extends DataSetVO, LVO extends IDataSetListVO, VO extends IDataSetVO> {

	@SuppressWarnings( "unused" )
	private static final Logger logger = LoggerFactory.getLogger( AbstractDatasetAdapter.class );

	private final T dataset;

	protected String language = null;
	
	protected boolean langFallback = false;

	public String getLanguage() {
		return language;
	}

	public void setLanguage( String language ) {
		this.language = language;
	}

	private AbstractDatasetAdapter( T adapterObject ) {
		this.dataset = adapterObject;
	}

	public AbstractDatasetAdapter( T adapterObject, LVO adaptee ) {
		this( adapterObject );
		this.copyValues( adaptee );
		this.copyValues( adaptee, this.dataset );
	}

	public AbstractDatasetAdapter( T adapterObject, VO adaptee ) {
		this( adapterObject );
		this.copyValues( adaptee );
		this.copyValues( adaptee, this.dataset );
	}

	private AbstractDatasetAdapter( T adapterObject, String language ) {
		this(adapterObject, language, false);
	}
	
	private AbstractDatasetAdapter( T adapterObject, String language, boolean langFallback ) {
		this.dataset = adapterObject;
		this.language = language;
		this.langFallback = langFallback;
	}

	public AbstractDatasetAdapter( T adapterObject, LVO adaptee, String language ) {
		this(adapterObject, adaptee, language, false);
	}
	
	public AbstractDatasetAdapter( T adapterObject, LVO adaptee, String language, boolean langFallback ) {
		this( adapterObject, language, langFallback );
		this.copyValues( adaptee );
		this.copyValues( adaptee, this.dataset );
	}

	public AbstractDatasetAdapter( T adapterObject, VO adaptee, String language ) {
		this( adapterObject, language );
		this.copyValues( adaptee );
		this.copyValues( adaptee, this.dataset );
	}

	/**
	 * Copy the values from the value <b>AND</b> the list value object
	 * to the adapter data set.
	 * 
	 * @param src
	 *            source object
	 * @param dst
	 *            destination data set
	 */
	protected abstract void copyValues( VO src, T dst );

	/**
	 * Copy the values from the list value object
	 * to the adapter data set
	 * 
	 * @param src
	 *            source object
	 * @param dst
	 *            destination data set
	 */
	protected abstract void copyValues( LVO src, T dst );

	private final void copyValues( IDataSetVO src ) {
		this.copyValues( (IDataSetListVO) src );
		LStringAdapter.copyLStrings( src.getDescription(), this.dataset.getDescription(), this.language, this.langFallback );
	}

	private final void copyValues( IDataSetListVO src ) {

		this.dataset.setUuid( src.getUuidAsString() );
		this.dataset.setDataSetVersion( src.getDataSetVersion() );
		this.dataset.setPermanentUri( src.getPermanentUri() );

		LStringAdapter.copyLStrings( src.getName(), this.dataset.getName(), this.language, this.langFallback );

		try {
			this.dataset.setClassification( new ClassificationAdapter( src.getClassification() ) );
		}
		catch ( Exception e ) {
		}

		this.dataset.setSourceId( src.getSourceId() );
		this.dataset.setHref( src.getHref() );
		
		if (src.getDuplicates().size() > 0)
			this.dataset.setDuplicates(src.getDuplicates());
	}

	public T getDataSet() {
		return dataset;
	}

	public boolean isLangFallback() {
		return langFallback;
	}

	public void setLangFallback(boolean langFallback) {
		this.langFallback = langFallback;
	}

}

Node/src/main/java/de/iai/ilcd/model/adapter/dataset/ContactVOAdapter.java
package de.iai.ilcd.model.adapter.dataset;

import de.fzk.iai.ilcd.service.client.impl.vo.dataset.ContactDataSetVO;
import de.fzk.iai.ilcd.service.model.IContactListVO;
import de.fzk.iai.ilcd.service.model.IContactVO;
import de.iai.ilcd.model.adapter.LStringAdapter;

/**
 * Adapter for Contacts
 */
public class ContactVOAdapter extends AbstractDatasetAdapter<ContactDataSetVO, IContactListVO, IContactVO> {

	/**
	 * Create adapter for {@link IContactListVO contact list value object}
	 * 
	 * @param adaptee
	 *            list value object to adapt
	 */
	public ContactVOAdapter( IContactListVO adaptee ) {
		super( new ContactDataSetVO(), adaptee );
	}

	/**
	 * Create adapter for the {@link IContactVO contact value object}
	 * 
	 * @param adaptee
	 *            value object to adapt
	 */
	public ContactVOAdapter( IContactVO adaptee ) {
		super( new ContactDataSetVO(), adaptee );
	}

	/**
	 * Create adapter for {@link IContactListVO contact list value object}
	 * 
	 * @param adaptee
	 *            list value object to adapt
	 */
	public ContactVOAdapter( IContactListVO adaptee, String language ) {
		super( new ContactDataSetVO(), adaptee, language );
	}

	/**
	 * Create adapter for {@link IContactListVO contact list value object}
	 * 
	 * @param adaptee
	 *            list value object to adapt
	 */
	public ContactVOAdapter( IContactListVO adaptee, String language, boolean langFallback ) {
		super( new ContactDataSetVO(), adaptee, language, langFallback );
	}

	/**
	 * Create adapter for the {@link IContactVO contact value object}
	 * 
	 * @param adaptee
	 *            value object to adapt
	 */
	public ContactVOAdapter( IContactVO adaptee, String language ) {
		super( new ContactDataSetVO(), adaptee, language );
	}

	/**
	 * Create adapter for the {@link IContactVO contact value object}
	 * 
	 * @param adaptee
	 *            value object to adapt
	 */
	public ContactVOAdapter( IContactVO adaptee, String language, boolean langFallback ) {
		super( new ContactDataSetVO(), adaptee, language, langFallback );
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected void copyValues( IContactListVO src, ContactDataSetVO dst ) {
		dst.setEmail( src.getEmail() );

		dst.setPhone( src.getPhone() );

		dst.setWww( src.getWww() );

		LStringAdapter.copyLStrings( src.getShortName(), dst.getShortName(), this.language, this.langFallback );
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected void copyValues( IContactVO src, ContactDataSetVO dst ) {
		this.copyValues( (IContactListVO) src, dst );

		dst.setCentralContactPoint( src.getCentralContactPoint() );
		dst.setFax( src.getFax() );
	}

}

Node/src/main/java/de/iai/ilcd/model/common/DataSet.java
package de.iai.ilcd.model.common;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.ElementCollection;
import javax.persistence.Embedded;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.MapKeyColumn;
import javax.persistence.MappedSuperclass;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrePersist;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.persistence.Version;

import org.apache.commons.collections.CollectionUtils;
import org.apache.commons.lang.StringUtils;

import de.fzk.iai.ilcd.service.client.impl.vo.dataset.DataSetVO;
import de.fzk.iai.ilcd.service.model.IDataSetVO;
import de.fzk.iai.ilcd.service.model.common.IMultiLangString;
import de.iai.ilcd.configuration.ConfigurationService;
import de.iai.ilcd.model.dao.DataSetDao;
import de.iai.ilcd.model.datastock.DataStock;
import de.iai.ilcd.model.datastock.RootDataStock;
import de.iai.ilcd.model.source.Source;
import de.iai.ilcd.util.lstring.IStringMapProvider;
import de.iai.ilcd.util.lstring.MultiLangStringMapAdapter;
import de.iai.ilcd.webgui.controller.util.ExportMode;
import de.iai.ilcd.xml.zip.ZipArchiveBuilder;
import eu.europa.ec.jrc.lca.commons.domain.ILongIdObject;

/**
 * 
 * @author clemens.duepmeier
 */
@MappedSuperclass
public abstract class DataSet implements Serializable, IDataSetVO, ILongIdObject {

	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue( strategy = GenerationType.IDENTITY )
	private Long id;

	// we use the field branch for optimistic concurrent locking;
	// i.e. collisions of concurrent updates will look for incremented branch numbers
	// branch will be incremented with every update of the data set
	@Version
	protected int branch = 0;

	// // if it's an remote data set node contains information about the remote network node
	// @Transient
	// private NetworkNode sourceNode=null;
	@Transient
	private String href;

	// we need this, if our data sets will be send to other servers, tools
	@Transient
	private String sourceId = ConfigurationService.INSTANCE.getNodeId();

	@ElementCollection
	@Column( name = "value", columnDefinition = "TEXT" )
	@MapKeyColumn( name = "lang" )
	protected final Map<String, String> name = new HashMap<String, String>();

	/**
	 * Adapter for API backwards compatibility.
	 */
	@Transient
	protected final MultiLangStringMapAdapter nameAdapter = new MultiLangStringMapAdapter( new IStringMapProvider() {

		@Override
		public Map<String, String> getMap() {
			return DataSet.this.name;
		}
	} );

	@Embedded
	protected Uuid uuid = new Uuid();

	@ElementCollection
	@Column( name = "value", columnDefinition = "TEXT" )
	@MapKeyColumn( name = "lang" )
	protected final Map<String, String> description = new HashMap<String, String>();

	/**
	 * Classifications
	 */
	@OneToMany( cascade = CascadeType.ALL )
	@JoinTable
	private final List<Classification> classifications = new ArrayList<Classification>();

	@ManyToOne
	@JoinColumn( name = "root_stock_id" )
	private RootDataStock rootDataStock;

	protected String permanentUri;

	@Embedded
	protected DataSetVersion version;

	@Enumerated( EnumType.STRING )
	protected DataSetState releaseState = DataSetState.UNRELEASED;

	@ManyToMany( fetch = FetchType.LAZY )
	protected Set<Language> supportedLanguages = new HashSet<Language>();

	@Temporal( TemporalType.TIMESTAMP )
	private Date importDate = null;

	@OneToOne( cascade = CascadeType.ALL, fetch = FetchType.LAZY )
	@JoinColumn( name = "XMLFILE_ID" )
	XmlFile xmlFile;

	/**
	 * Flag to indicate if this is the most recent version of this data set
	 */
	@Basic
	private boolean mostRecentVersion;

	/**
	 * Cache for the name column - used for filtering &amp; order in queries.
	 * 255 character limit should be sufficient.
	 */
	@Basic
	@Column( name = "name_cache", length = 255 )
	private String nameCache;

	/**
	 * Cache for the classification - used for filtering &amp; order in queries.
	 * 100 character limit should be sufficient.
	 */
	@Basic
	@Column( name = "classification_cache", length = 100 )
	private String classificationCache;

	@Transient
	protected Set<DataSet> dependencies = null;
	
	/**
	 * Get all datasets that are linked from this dataset
	 * 
	 * @return all datasets that are linked from this dataset
	 */
	public Set<DataSet> getDependencies() {
		if (this.dependencies == null) {
			this.dependencies = new HashSet<DataSet>();
			return this.dependencies;
		}
		else return this.dependencies;
	}
	
	public void setDependencies(Set<DataSet> dependencies) {
		this.dependencies = dependencies;
	}
	
	
	/**
	 * Get all data stocks that this data set is contained in
	 * 
	 * @return data stocks that this data set is contained in
	 */
	public abstract Set<DataStock> getContainingDataStocks();

	/**
	 * Get all data stocks that this data set is contained in as one String
	 * 
	 * @return data stocks that this data set is contained in as one String
	 */
	public String getContainingDataStocksAsString() {
		if (this.getContainingDataStocks() != null) {
			StringBuilder builder = new StringBuilder();
			for (DataStock stock : this.getContainingDataStocks()) {
				if (builder.length() != 0) {
					builder.append(";");
				}
				builder.append(stock.getName());
			}
			return builder.toString();
		} else
			return null;
	}

	/**
	 * Add the data set to the data stock. Only do the <code>addXXXX</code> call,
	 * everything else is done be {@link #addToDataStock(DataStock)}.
	 * 
	 * @param stock
	 *            stock to add to
	 */
	protected abstract void addSelfToDataStock( DataStock stock );

	/**
	 * Remove the data set from the data stock. Only do the <code>removeXXXX</code> call,
	 * everything else is done be {@link #removeFromDataStock(DataStock)}.
	 * 
	 * @param stock
	 *            stock to add to
	 */
	protected abstract void removeSelfFromDataStock( DataStock stock );

	/**
	 * Get the type of this data set
	 * 
	 * @return type of this data set
	 */
	public abstract DataSetType getDataSetType();

	/**
	 * Add to data stock
	 * 
	 * @param stock
	 *            stock to add to
	 */
	public final boolean addToDataStock( DataStock stock ) {
		final Set<DataStock> containingDataStocks = this.getContainingDataStocks();
		if ( !containingDataStocks.contains( stock ) ) {
			containingDataStocks.add( stock );
			this.addSelfToDataStock( stock );
			return true;
		} else 
			return false;
	}

	/**
	 * Remove from data stock
	 * 
	 * @param stock
	 *            stock to remove from
	 */
	public final boolean removeFromDataStock( DataStock stock ) {
		final Set<DataStock> containingDataStocks = this.getContainingDataStocks();
		if ( containingDataStocks.contains( stock ) ) {
			containingDataStocks.remove( stock );
			this.removeSelfFromDataStock( stock );
			return true;
		} else 
			return false;
	}

	@Override
	public Long getId() {
		return this.id;
	}

	public void setId( Long id ) {
		this.id = id;
	}

	/**
	 * Get the root data stock
	 * 
	 * @return the root data stock
	 */
	public RootDataStock getRootDataStock() {
		return this.rootDataStock;
	}

	/**
	 * Set the root data stock
	 * 
	 * @param rootDataStock
	 *            the root data stock to set
	 */
	public void setRootDataStock( RootDataStock rootDataStock ) {
		this.rootDataStock = rootDataStock;
	}

	// public NetworkNode getSourceNode() {
	// return sourceNode;
	// }
	//
	// public void setSourceNode(NetworkNode sourceNode) {
	// this.sourceNode = sourceNode;
	// }

	/**
	 * Write the {@link #getName() name} default value
	 * to the cache field.
	 */
	@PrePersist
	protected void applyDataSetCache() {
		this.nameCache = StringUtils.substring( this.getNameAsStringForCache(), 0, 255 );
		if ( CollectionUtils.isNotEmpty( this.classifications ) ) {
			this.classificationCache = StringUtils.substring( this.getClassificationHierarchyAsStringForCache(), 0, 100 );
		}
		else {
			this.classificationCache = null;
		}

	}

	public int getBranch() {
		return this.branch;
	}

	public void setBranch( int branch ) {
		this.branch = branch;
	}

	/**
	 * Get the hierarchy of classification as string. May be overridden by
	 * sub-classes if {@link #getClassification()} shall not represent
	 * the hierarchy.
	 * 
	 * @return delegates to {@link #getClassification()}.{@link Classification#getClassHierarchyAsString()
	 *         getClassHierarchyAsString()}
	 */
	protected String getClassificationHierarchyAsStringForCache() {
		final Classification classification = this.getClassification();
		if ( classification != null ) {
			return classification.getClassHierarchyAsString();
		}
		return null;
	}

	/**
	 * Get the name as string. May be overridden by sub-classes if {@link #getName()} shall not represent the name.
	 * 
	 * @return delegates to {@link #getName()}.{@link MultiLanguageString#getDefaultValue() getDefaultValue()}
	 */
	protected String getNameAsStringForCache() {
		if ( this.name != null ) {
			return this.nameAdapter.getDefaultValue();
		}
		return null;
	}

	/**
	 * Determine if this is the most recent version of this data set
	 * 
	 * @return <code>true</code> if this is the most recent version of this data set, else <code>false</code>
	 */
	public boolean isMostRecentVersion() {
		return this.mostRecentVersion;
	}

	/**
	 * Set the flag to indicate if this data set is the most recent version of the data set

Node/src/main/java/de/iai/ilcd/util/IDatasetListBackingBean.java
package de.iai.ilcd.util;

import de.iai.ilcd.model.common.DataSet;
import de.iai.ilcd.model.datastock.IDataStockMetaData;
import de.iai.ilcd.webgui.controller.admin.StockHandler;

public interface IDatasetListBackingBean<E extends DataSet> {

	public StockHandler getStockHandler();

	public DependenciesOptions getDependenciesOptions();

	public IDataStockMetaData getMoveTarget();

	public void setMoveTarget(IDataStockMetaData moveTarget);

}

Node/src/main/webapp/admin/datasets/include/confirmDialog.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml" xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core" xmlns:c="http://java.sun.com/jsp/jstl/core" xmlns:p="http://primefaces.org/ui"
	xmlns:ui="http://java.sun.com/jsf/facelets">

	<ui:param name="dialogId" value="#{dataTableId}#{action}Confirm" />
	<p:dialog header="#{dialogHeader}" 
		severity="alert" modal="true" widgetVar="#{dialogId}" resizable="false" appendTo="@form">
		<p:ajax event="open"
			listener="#{assignRemoveDataSetHandler.resetForce()}" />
		<p:ajax disabled="#{allMode == 'true' and jobCheckbox == 'false'}" event="open" update="@(.#{dataTableId}#{action}panel)"
			listener="#{assignRemoveDataSetHandler.batchNeeded(lazyDataModel, backingBean)}" />

			<div style="padding-top: 15px; padding-bottom: 15px;">
				<h:outputText value="#{dialogMessage}" style="white-space: pre-wrap" />
			</div>

			<h:panelGroup rendered="#{action=='moveSelected'}">
				<div>
					<h:outputText value="#{i18n['admin.stock.move.target']}" />
					<p:spacer width="10px" />
					<p:selectOneMenu value="#{backingBean.moveTarget}" converter="#{dsMetaConverter}">
						<f:selectItem itemLabel="#{i18n['common.select.hint']}" noSelectionOption="true" />
						<f:selectItems value="#{backingBean.availableStocksForMove}" var="stock" itemLabel="#{stock.name}"
							itemValue="#{stock}" />
					</p:selectOneMenu>
				</div>
				<p:spacer height="10px" />
			</h:panelGroup>
				
		<ui:include
			src="/admin/datasets/include/dependenciesDropListInclude.xhtml">
			<ui:param name="backingBean" value="#{backingBean}" />
			<ui:param name="showDependenciesOption"
				value="#{showDependenciesOption}" />
		</ui:include>

		<div class="confirmDlgButtons">
			<p:spacer height="10px" />
			<c:choose>
				<c:when
					test="#{conf.displayConfig.showDependenciesOptions and showDependenciesOption}">
					<p:commandButton value="#{actionDialogCancelLabel}"
						action="#{backingBean.dependenciesOptions.resetDependenciesOption()}"
						oncomplete="PF('#{dialogId}').hide();" />
				</c:when>
				<c:otherwise>
					<p:commandButton value="#{actionDialogCancelLabel}"
						onclick="PF('#{dialogId}').hide();" />
				</c:otherwise>
			</c:choose>
			<h:panelGroup  id="#{dataTableId}#{action}panel" styleClass="#{dataTableId}#{action}panel">
			
				<p:selectBooleanCheckbox rendered="#{jobCheckbox == 'true'}"  id = "#{dataTableId}#{action}batchNeeded" style="float: left;margin-top: 11px;"
					value="#{assignRemoveDataSetHandler.batchNeeded}"
					itemLabel="#{i18n['admin.stock.createBatchAsJob']}">
					<p:ajax update="#{dataTableId}#{action}panel" />
				</p:selectBooleanCheckbox>
				<p:tooltip rendered="#{jobCheckbox == 'true'}" for="#{dataTableId}#{action}batchNeeded" mouseTracking="true" adjustX="10"
					adjustY="20" value="Recommended for large datasets, more than 500." />

				<p:commandButton id="#{dialogId}OkButton"
					rendered="#{allMode == 'true'}" process="@this" ajax="false"
					value="#{actionDialogOKLabel}"
					action="#{assignRemoveDataSetHandler[action]}" />

				<p:commandButton
					rendered="#{allMode != 'true' and not assignRemoveDataSetHandler.batchNeeded}"
					process="@this" ajax="false" value="#{actionDialogOKLabel}"
					action="#{backingBean[action]}" />

				<p:commandButton
					rendered="#{assignRemoveDataSetHandler.batchNeeded and jobCheckbox == 'true'}"
					process="@this" ajax="false" value="#{actionDialogOKLabel}"
					action="#{assignRemoveDataSetHandler.batch(lazyDataModel, action)}" />
			</h:panelGroup>

		</div>
	</p:dialog>
</ui:composition>

Node/src/main/webapp/admin/datasets/include/contactListInclude.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	template="datasetListTemplate.xhtml">

	<ui:param name="dataTableId" value="#{empty dtId ? 'contactTable' : dtId}" />
	<ui:param name="exportFileName" value="contactTable" />
	<ui:param name="publicShowFacelet" value="showContact" />
	<ui:param name="nameFilterField" value="" />

	<ui:define name="columns">

		<p:column headerText="#{i18n['common.dataset.classif']}" rendered="#{conf.displayConfig.showManageDatasetClassification}">
		    <h:outputText value="#{dataset.classification.classHierarchyAsString}" />
		</p:column>

	</ui:define>
</ui:composition>

Node/src/main/webapp/admin/datasets/include/datasetListTemplate.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:c="http://java.sun.com/jsp/jstl/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:ui="http://java.sun.com/jsf/facelets">

<!--
Parameters for this composition:
	via ui:define:
		columns
	via ui:param:
		mostRecentVersionOnlyFilter
		includeMessages
		omitForm
		dataTableId
		backingBean
		lazyDataModel
		selectionProperty
		nameFilterField
		nameFilterActionMethod 
		selectedActionButtonLabel
		actionDialogHeader
		actionDialogMessage
		actionDialogOKLabel
		actionDialogCancelLabel
		actionDialogOKActionMethod
		showDependenciesOption
		moveControls
		publicShowFacelet
		initialRows (optional, default is 15)
		nameProperty (optional, default is name.defaultValue)
		namePropertyField (mandatory if nameProperty is declared, else optional and ignored if set)
		forceDs (optional, override data stock link -> $root$ for root data stock)
		datasetType
-->
	<c:if test="#{not omitForm}">
		<h:form id="#{dataTableId}Form" prependId="false">
			<ui:include src="datasetListTemplateDataTable.xhtml" />
		</h:form>
	</c:if>
	<c:if test="#{omitForm}">
		<ui:include src="datasetListTemplateDataTable.xhtml" />
	</c:if>
</ui:composition>

Node/src/main/webapp/admin/datasets/include/dependenciesDropListInclude.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	xmlns:shiro="http://shiro.apache.org/tags"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:c="http://java.sun.com/jsp/jstl/core">
	<h:panelGroup
		rendered="#{conf.displayConfig.showDependenciesOptions and showDependenciesOption}">
		<p:fieldset id = "#{dialogId}Header" legend="#{i18n['admin.advanced.options']}"
			toggleable="true" collapsed="true" style="font-size:75%;">
			<h:panelGrid columns="1" style="margin-bottom:10px" cellpadding="5">
				<h:outputText value="#{i18n['admin.dependencies']}" />
				<p:selectOneRadio layout="pageDirection"
					value="#{backingBean.depOption}"
					converter="#{dependenciesOptionConverter}"
					valueChangeListener="#{backingBean.depOptionChange}">
					<f:selectItems
						value="#{backingBean.dependenciesOptions.dependenciesOptionsValues}"
						var="depOption" itemValue="#{depOption}"
						itemLabel="#{i18n['admin.dependencies.'.concat(depOption)]}" />
				</p:selectOneRadio>
			</h:panelGrid>
		</p:fieldset>
	</h:panelGroup>
</ui:composition>

Node/src/main/webapp/admin/datasets/include/flowListInclude.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	template="datasetListTemplate.xhtml">

	<ui:param name="dataTableId" value="#{empty dtId ? 'flowTable' : dtId}" />
	<ui:param name="exportedFileName" value="flowTable" />
	<ui:param name="nameFilterField" value="" />

	<ui:define name="columns">

		<p:column headerText="#{i18n['common.type']}">
		    <h:outputText value="#{dataset.type.value}" />
		</p:column>
		
		<p:column headerText="#{i18n['common.dataset.classif']}" rendered="#{conf.displayConfig.showManageDatasetClassification}">
		    <h:outputText rendered="#{dataset.elementaryFlow}" value="#{dataset.categorization.classHierarchyAsString}" />
		    <h:outputText rendered="#{not dataset.elementaryFlow}" value="#{dataset.classification.classHierarchyAsString}" />
		</p:column>

	</ui:define>
</ui:composition>